Milestone2
yahir91/Calculator-App pull request #2
Opened 2021-02-22 22:18 UTC by yahir91

In this milestone, I created:

- Four javascript files inside the components folder.
- In each file, I created a stateless functional function.
- I build a static calculator template.

2021-02-22 23:23 UTC, Spayco requested changes
# Changes Requested 

Hello! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] The `Button` component should display only 1 button, not multiple, the props shouldn't be an array of strings, but instead a string (prop should be called "name") ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/validateAsString.png))
- [ ] in your `ButtonPanel` component, instead of making arrays inside the button, wrap each row in a div and have each button use the `Button` component individually. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/buttonPanel/buttons.png))

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-23 18:23 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

sorry if it wasn't clear earlier, I'll try to describe the issue better below 👇 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-23 18:23 UTC, SpaYco commented on src/components/Button.js
>  );
- [ ] you shouldn't use the `map` function here, this component should receive 1 string containing the name of the button, and not multiple strings in an array.

2021-02-23 18:23 UTC, Spayco commented on src/components/ButtonPanel.js
> +  );
- [ ] why are you using the [`React.fragment`](https://reactjs.org/docs/fragments.html) if you're wrapping the component in a div? `React.fragment` is supposed to make your components return elements with nothing wrapping them, so wrapping it in a div destroys its purpose, either use the div or the fragment.

- [ ] Use divs here to create multiple rows of `Button` components, example: 

```jsx
<div>
    <Button name"AC" >
    <Button name"+/-" >
    <Button name"%" >
    <Button name"/" >
  </div>
  <div>
    <Button name"7" >
    <Button name"8" >
    <Button name"9" >
    <Button name"X" >
  </div>
  <div>
    <Button name"4" >
    <Button name"5" >
    <Button name"6" >
    <Button name"-" >
  </div>
  <div>
    <Button name"1" >
    <Button name"2" >
    <Button name"3" >
    <Button name"+" >
  </div>
  <div>
    <Button name"0" >
    <Button name"." >
    <Button name"=" >
  </div>
```

2021-03-03 19:13 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****


 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2021-03-03 19:55 UTC, merged