Logic added to the calculator
yahir91/Calculator-App pull request #3
Opened 2021-03-03 19:58 UTC by yahir91

In this milestone, I added the logic to the calculator with two functions operate and calculate.

2021-03-04 00:34 UTC, bellom requested changes
## Hi @yahir91  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-03-04 00:34 UTC, bellom commented on src/logic/operate.js
> +    case 'X':
You might wanna use lowercase `x` to match the size with the rest of the operator.

2021-03-04 00:34 UTC, bellom commented on src/logic/operate.js
> +      return firstNumber * Big(-1);
Job well done but you don't have to do the calculating yourself, that where the use of `big` comes in -> [big js library](https://github.com/favio41/big-js#readme)
example: case division will be -> `firstNumber.minus(secondNumber)`

2021-03-04 00:41 UTC, bellom commented
@yahir91, Noted
This CRR, has been mistakenly marked as approved.
I already reach out to the dev guys to revert it.

Sorry for this.

2021-03-05 17:23 UTC, yahir91 commented
Thank you for the review, x has been changed to lowercase, and the Big.js methods have been used properly

2021-03-06 00:16 UTC, uche-inyama requested changes
## Changes Required

### Hi @yahir91 :wave: 

You are almost done. I have a left of comment below, update operate.js accordingly.

#### That's it, make the change and submit another form for a code review.


### Have a great day :slightly_smiling_face: 


#### ``` Uchechukwu Henry Inyama ```

2021-03-06 00:16 UTC, uche-inyama commented on src/logic/operate.js
> +
You should also create a new instance of Big for the secondNumber. 

```
    const secondNumber = new Big(numberTwo)
````

2021-03-06 12:44 UTC, arslanbisharat approved these changes
# Approved 🥇 

Thank you for submitting this project. You have done a great job!

- [x] Your commit messages are very descriptive too. I am very happy to see that.  👏 
- [x] No Linter error found. 👏 
- [x] Met Minimum requirements to pass the project.  

I am very happy to review your project. Looking forward to amazing new projects from your side. 

**Best,
Arslan Bisharat**
_You can always contact me on slack at @arslanbisharat 📞_

2021-03-25 07:05 UTC, closed without merging